#!/usr/bin/env zsh

echo "Starting Zsh configuration setup..."

CONFIG_PATH="$(pwd)"

cat <<EOF > ~/.zshrc
# --- ZSH CONFIGURATION GENERATED BY setup_env.sh ---

export CONFIG_PATH="${CONFIG_PATH}"

source "\$CONFIG_PATH/core/aliases.sh"
source "\$CONFIG_PATH/core/shell.sh"

# Dynamically source all .sh files in the extensions directory
for extension_file in "\$CONFIG_PATH/extensions/"*.sh; do
  if [[ -f "\$extension_file" ]]; then
    source "\$extension_file"
  fi
done

# --- END OF ZSH CONFIGURATION ---
EOF

source ~/.zshrc

echo "Successfully recreated ~/.zshrc."

